# Generated by Django 2.2.5 on 2019-09-20 09:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dblayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='user',
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skilldescription',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilldescription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='companyName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='skillName',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=None), size=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dblayer.SkillCategory')),
            ],
        ),
    ]
